# Generated by Django 2.2.2 on 2019-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190616_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_mod',
            field=models.BooleanField(default=False, help_text='Designates that this user has extra power to flag, report, and ban users / posts.', verbose_name='Moderator Status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates that this user can log into the admin site.', verbose_name='Staff Status'),
        ),
    ]
