# Generated by Django 2.2.2 on 2019-06-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190621_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
