# Generated by Django 2.2.2 on 2019-07-02 22:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Flag',
                'verbose_name_plural': 'Flags',
                'db_table': 'flags',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(max_length=64)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(app_label='posts'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'likes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
