# Generated by Django 2.2.2 on 2019-07-02 22:52

import api.config.storage_backends
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=15, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField(default='')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Unique UUID string that represents the post', populate_from=['title'], primary_key=True, serialize=False, unique=True)),
                ('published', models.BooleanField(default=False, help_text='Is the post published and public')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('last_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='Last Modified Time')),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=api.config.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('header', models.ImageField(blank=True, null=True, storage=api.config.storage_backends.PrivateMediaStorage(), upload_to='')),
                ('header_caption', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('md_content', models.TextField(default='', help_text='Markdown content for the blog post', verbose_name='Markdown Content')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created'],
            },
        ),
    ]
