# Generated by Django 2.2.2 on 2019-06-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190617_0323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='post',
            name='header_caption',
            field=models.CharField(default='', max_length=128),
        ),
    ]
