# Generated by Django 2.2.2 on 2019-06-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190620_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_caption',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
