# Generated by Django 2.2.2 on 2019-06-21 00:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190621_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
